// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using imgurplusbot.dal.EF;

namespace imgurplusbot.dal.Migrations
{
    [DbContext(typeof(ImgurPlusContext))]
    [Migration("20200404135918_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("imgurplusbot.dal.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TgId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("imgurplusbot.dal.Models.UserUpload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DeleteDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgurDeleteHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgurLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("TgFileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserUploads");
                });
#pragma warning restore 612, 618
        }
    }
}
